### ISSUE TITLE
Unweighted 

### ISSUE THREAD

**Issue by dekdekdek1** [dekdekdek1/BPS1214#1]

**Comment by dekdekdek1** [comment]
@Huade I used the function prop.table for the unweighted. I think the code may still be a little more complicated than it has to be, and the column headings are [1] and [2] rather than male and female, would you like me to try to change that?

**Comment by dekdekdek1** [comment]
@Huade This recode should work, let me know if you think there's a better way of doing it!

**Comment by Huade** [comment]
`recode` looks good to me!

**Comment by Huade** [comment]
It seems you have unweighted percentage ready. Feel free to close this issue.
